#!/usr/bin/env zsh

if [ -f ~/.shell.local.before ]; then
	source ~/.shell.local.before
fi

if [ -f ~/.zshrc.local.before ]; then
	source ~/.zshrc.local.before
fi

source ~/.dotfiles/shells/all/bootstrap.sh
source ~/.dotfiles/shells/zsh/plugins.zsh
source ~/.dotfiles/shells/zsh/settings.zsh
source ~/.dotfiles/shells/all/aliases.sh

if [ -f ~/.zshrc.local.after ]; then
	source ~/.zshrc.local.after
fi

if [ -f ~/.shell.local.after ]; then
	source ~/.shell.local.after
fi
