#!/bin/bash

apm_packages=(
	Sublime-Style-Column-Selection
	advanced-open-file
	atom-beautify
	atom-monokai-soda
	atom-runner
	atom-ternjs
	auto-detect-indentation
	auto-semicolon
	auto-update-packages
	autocomplete-emojis
	autocomplete-modules
	ava
	base16-syntax
	base64
	block-comment-plus
	change-case
	civic-syntax
	docblockr
	editorconfig
	emmet
	file-icons
	gist-it
	git-plus
	git-time-machine
	highlight-selected
	language-haproxy
	language-ini
	language-nginx
	less-than-slash
	linter
	linter-eslint
	linter-jsonlint
	linter-markdown
	linter-php
	linter-proselint
	linter-pyflakes
	linter-shellcheck
	linter-stylelint
	linter-swiftc
	linter-xmllint
	merge-conflicts
	native-ui
	oceanic-next
	octocat-syntax
	open-recent
	pigments
	project-plus
	react
	revert-buffer
	set-syntax
	smart-quotes-plus
	sort-lines
	toggle-quotes
	travis-ci-status
	url-encode
)

apm install "${apm_packages[@]}"
