#!/usr/bin/env bash

set -e

DEFAULT_CONFIG="default"
CONFIG_SUFFIX=".conf.yaml"

ANTIGEN_DIR="shells/zsh/antigen"
DOTBOT_DIR="meta/dotbot"
DOTBOT_BREWFILE_DIR="meta/dotbot-brewfile"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

function update_submodule() {
	git -C "$1" submodule sync --quiet --recursive
	git submodule update --init --recursive "$1"
}

cd "${BASEDIR}"
update_submodule "$ANTIGEN_DIR"
update_submodule "$DOTBOT_DIR"
update_submodule "$DOTBOT_BREWFILE_DIR"

for conf in ${DEFAULT_CONFIG} "${@}"; do
	"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-brewfile -c "meta/${conf}${CONFIG_SUFFIX}"
done
