name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run shellcheck
      run: shellcheck shells/bash_profile shells/bashrc shells/**/*.sh shells/**/*.bash
